import { cleanup, act, renderHook } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { useDropGame } from './useDropGame'
afterEach(() => { cleanup(); vi.useRealTimers() })
const advance = (time: number) => act(() => vi.advanceTimersByTime(time))
describe('drop presentation lifecycle', () => {
  it('locks rapid taps and commits only after drop, clear and gravity', () => {
    vi.useFakeTimers()
    const feedback = vi.fn()
    const { result } = renderHook(() => useDropGame(false, feedback))
    act(() => { result.current.drop(2); result.current.drop(2) })
    expect(result.current.busy).toBe(true)
    expect(result.current.state.moves).toBe(0)
    expect(result.current.state.current).toBe('blue')
    expect(result.current.state.next).toBe('blue')
    advance(420)
    expect(result.current.display.wave?.cells).toHaveLength(3)
    advance(580); advance(420)
    expect(result.current.state.moves).toBe(1)
    expect(result.current.state.cleared).toBe(3)
    expect(result.current.busy).toBe(false)
    expect(feedback.mock.calls.map(call => call[0])).toEqual([0, 1])
  })
  it('freezes while paused and resumes without consuming another cat', () => {
    vi.useFakeTimers()
    const { result, rerender } = renderHook(({ paused }) => useDropGame(paused, vi.fn()), { initialProps: { paused: false } })
    act(() => result.current.drop(2))
    rerender({ paused: true }); advance(5000)
    expect(result.current.state.moves).toBe(0)
    act(() => result.current.drop(0))
    rerender({ paused: false }); advance(420); advance(580); advance(420)
    expect(result.current.state.moves).toBe(1)
  })
  it('cancels pending resolution on restart and unmount', () => {
    vi.useFakeTimers()
    const { result, unmount } = renderHook(() => useDropGame(false, vi.fn()))
    act(() => result.current.drop(2)); advance(420)
    act(() => result.current.reset()); advance(5000)
    expect(result.current.state.moves).toBe(0)
    expect(result.current.display.wave).toBeUndefined()
    expect(result.current.busy).toBe(false)
    act(() => result.current.drop(0)); unmount()
    expect(vi.getTimerCount()).toBe(0)
  })
  it('ignores invalid drops and animates a move without a match', () => {
    vi.useFakeTimers()
    const { result } = renderHook(() => useDropGame(false, vi.fn()))
    act(() => result.current.drop(-1))
    expect(result.current.busy).toBe(false)
    act(() => result.current.drop(5)); advance(420)
    expect(result.current.state.moves).toBe(1)
    expect(result.current.state.cleared).toBe(0)
  })
  it('starts the clock on first drop, pauses it during animation, and grants three final drops once', () => {
    vi.useFakeTimers()
    const { result, rerender } = renderHook(({ paused }) => useDropGame(paused, vi.fn()), { initialProps: { paused: false } })
    advance(150000)
    expect(result.current.secondsLeft).toBe(120)
    act(() => result.current.drop(5)); advance(420)
    rerender({ paused: true }); advance(20000)
    expect(result.current.secondsLeft).toBe(120)
    rerender({ paused: false }); advance(120000)
    expect(result.current.failure).toBe('time')
    act(() => result.current.revive())
    expect(result.current.extraDrops).toBe(3)
    for (let i = 0; i < 3; i++) { act(() => result.current.drop(i)); advance(420); advance(580); advance(420) }
    expect(result.current.state.phase).toBe('failed')
    act(() => result.current.revive())
    expect(result.current.state.phase).toBe('failed')
    act(() => result.current.reset())
    expect(result.current.secondsLeft).toBe(120)
    expect(result.current.reviveUsed).toBe(false)
  })
})
